INSERT INTO NEWS VALUES (null,
                         'Syrian rebels launch Aleppo counter attack',
                         'Ilya',
                         'A rebel fighter part of the Jabhat Fatah al Sham, attends military training in the besieged rebel held Aleppo, Syria October 26, 2016.',
                         'Syrian rebels began a counter-attack in Aleppo on Friday with heavy shelling of government-held areas after a weeks-long Russian-backed offensive against besieged districts held by insurgents, rebels said.
The Syrian Observatory for Human Rights, a British-based group that reports on the war, also said that insurgents had set off several suicide car bombs on the western edge of Aleppo.
A Syrian military source said an insurgent attack in that area had been thwarted. A state TV station said the army had destroyed four car bombs.
The rebels aim to break a siege that government and allied militias imposed this summer with air support from the Russian air force. The rebel-held eastern districts of Aleppo have been subjected to a fierce bombardment since the army declared an offensive to capture the area last month.
"There is a general call-up for anyone who can bear arms," a senior official in the Levant Front rebel group, which fights under the Free Syrian Army (FSA) banner, told Reuters. "The preparatory shelling started this morning," he added.
The attack appeared to have been mostly launched by rebel fighters from outside the city against government forces that hold its western districts.
A spokesman for Ahrar al-Sham, a large Islamist rebel group, also said in a social networking message that an offensive on Aleppo had begun on Friday. Factions involved in the attack include Free Syrian Army groups and Jaish al-Fatah, an alliance of Islamist factions, the Levant Front official said.
Grad rockets were launched at Aleppo''s Nairab air base, said Zakaria Malahiji, head of the political office of the Aleppo-based Fastaqim rebel group, adding that it was going to be "a big battle" with all the insurgent groups there participating.
Heavy rebel bombardment, with more than 150 rockets and shells, struck districts on the southwest of the city, the Observatory reported. It said more than 15 civilians had been killed and 100 wounded by rebel shelling of government-held western Aleppo. State media reported that five civilians were killed.
The Observatory also said that Grad surface-to-surface rockets had struck Nairab air base and also locations around the Hmeimim air base, near Latakia. Syria''s civil war, now in its sixth year, pits President Bashar al-Assad, backed by Russia, Iran and Shi''ite militias from neighboring states, against mostly Sunni rebels including groups supported by Turkey, Gulf monarchies and the United States.
Aleppo, Syria''s most populous city before the war, has for years been split between a government-held western sector and the rebel-held east, which the army and its allies managed to put under siege this summer.
(Additional reporting by Tom Perry, Writing by Angus McDowall, Editing by Angus MacSwan)',
                         '2016-10-28');
INSERT INTO NEWS VALUES (NULL,
                         'Clinton holds lead, but pollsters say their job is harder',
                         'Ilya',
                         'Supporters touch Michelle Obama hand after she delivers a speech during a campaign rally in support of Hillary Clinton in Winston-Salem, North Carolina.',
                         'Many opinion polls show Democrat Hillary Clinton leading Republican Donald Trump in a tight race for the Nov. 8 U.S. presidential election, but any one of four factors may make the outcome harder to predict.
Among the challenges for pollsters: The historic unpopularity of both candidates, the potential Election Day voter response to the polls themselves, the growing abandonment of landlines for cellphones, and the rise of online polling.
Some high-profile stumbles worldwide - including opinion polls that missed Colombia''s Oct. 2 rejection of a peace deal - underscore how technological, social and cultural shifts have made polling more difficult than ever.
An average of polls compiled by RealClearPolitics.com shows former Secretary of State Clinton beating Trump, a businessman, by 5.4 percentage points. Highlighting the difficulties, the range varies from plus-13 for Clinton to a straight tie.
Trump has said the election is rigged against him and this week, in a Reuters interview, he accused media organizations of tilting the polls deliberately, but he has yet to offer any widely accepted evidence to back up these claims.
Voter turnout in the last few presidential elections has been about 60 percent. But given both candidates'' low overall popularity, turnout this year may fall to as low as 52 percent, said Cliff Zukin, a professor emeritus of political science at New Jersey''s Rutgers University and a former president of the American Association for Public Opinion Research.
That makes it hard to guess who might stay home.
"It''s always been difficult to simulate a likely electorate and I think that''s harder to do in 2016," Zukin said.
POLLING MAY AFFECT TURNOUT
A second pitfall is the effect of the polling itself on voters. Sociologists believe polls can weaken projected winners by making their supporters more confident of the outcome and, therefore, less likely to vote.
The percentage of Trump supporters who expect him to win has dropped to 49 percent in a Reuters/Ipsos poll conducted from Oct. 20-24, down from 74 percent from Sept. 16-20. Clinton supporters'' confidence rose at the same time.
If that leads to a higher turnout of Trump supporters than of Clinton supporters, it might affect the election outcome.
Pollsters caution, however, that the effect of polls on the electorate can only go so far.
    "If it were showing Clinton up by 2 points, then it''s certainly possible that it would be within the margin of error that Trump might win," said Douglas Schwartz, director of the Quinnipiac University Poll.
"But if you''re finding that all of these high-quality polls are showing Clinton consistently ahead, then I think you can trust them," he said.
CELLPHONES AN ISSUE
One of the biggest factors in polling today is the prevalence of cellphones. About half of Americans have only a cellphone and no landline, according to Federal Communications Commission data, more than double the number who were wireless-only in 2010.
This makes it harder and more expensive for pollsters to gather a truly random sample of opinions because U.S. law prohibits computerized auto-dialing (also known as robocalls) to cellphones and there is no central directory for cellphones.
Polling cellphones can costs 30 to 50 percent more than polling land lines due to requirements that the numbers be dialed manually, according to Pew Research Center estimates. This has led polling outfits to generally rely on lower sample sizes to come up with results.
Calls to cellphones are also more easily screened by their users, and as a result pollsters say they connect with just 10 percent of people they try to contact, down from 80 percent a few decades ago.
But Courtney Kennedy, director of survey research at Pew said, "In terms of data, the quality is better." Many respondents on cellphones are young and racially diverse, she said.','2016-10-29');

INSERT INTO NEWS VALUES (NULL,
                         'Internet providers now need permission to share or sell your web browsing data',
                          'Ilya',
                         'The U.S. Federal Communications Commission has finalized groundbreaking new rules that force all internet providers, like Verizon, Comcast and AT&T, to obtain explicit consent from subscribers before selling data about online behavior to third-party ...',
                         'The U.S. Federal Communications Commission has finalized groundbreaking new rules that force all internet providers, like Verizon, Comcast and AT&T, to obtain explicit consent from subscribers before selling data about online behavior to third-party marketers.
That includes information about what websites you visit, mobile location information, app usage and other potentially sensitive details inadvertently collected in the course of using the internet at home or on a smartphone.
The FCC rules don’t affect the way platforms like Google and Facebook use personal data for targeted advertising. Rather, companies that provide internet access are treated different from websites, in that they are providing a utility as defined by the network neutrality rules passed last year.
While the new ISP privacy rules are viewed by public interest advocates as a win for consumers, it’s still not clear how effective the regulations will be.
That’s largely because the current way online businesses notify and gain consent to collect user data is via privacy policies or license agreements that usually amount to long, arduous blocks of text on which everyone routinely clicks “Agree” in order to get past and then ignores.
If ISPs are able to fulfill the consent requirement this way, people may very well agree to data collection about their internet behavior without fully realizing what they’re agreeing to.
Still, broadband providers aren’t happy and would rather collect and use customer data without restriction.
“There is no sound reason to subject broadband providers to a different set of rules than other Internet companies,” said AT&T in a comment sent to the FCC, claiming broadband providers will be prevented from engaging in the lucrative digital advertising game.
AT&T announced plans to merge with Time Warner last weekend with the hope of expanding its online advertising operations, which could be affected by the new FCC rules.
Yet Google, which is scaling back its fiber program and totally dominates the online ad industry, also opposed the rules. In its comments to the FCC, Google said data ISPs collect about browsing history shouldn’t require opt-in consent from subscribers; the company doesn’t believe web browsing data contains sensitive information.
Still, the FCC rules are final. And if internet providers want to oppose them, they’ll have to take the agency to court.
Here are the basics of the new rules:
ISPs need to get consent, somehow, from subscribers before using or selling their sensitive data — browsing history, app usage, location information, financial data — to third parties, like online advertisers.
ISPs do not need permission from subscribers to share non-sensitive information, which includes IP addresses, email addresses, service tiers or bandwidth usage. But internet providers must create a way for subscribers to opt out of sharing that information if they so chose.
The new rules don’t require internet companies to gain consent to advertise other communications services they provide. So if Verizon wanted to market its home broadband service to a current mobile user, that would be fine. If Verizon wanted to share browsing data with other parts of the company that do not provide communications services, like Yahoo, it would have to get consent. And there’s no requirement to provide a way to opt out of internal marketing.','2016-10-29');

INSERT INTO NEWS VALUES (NULL,
                         'For Wade, Chicago homecoming a ''special'' moment',
                         'Ilya',
                         'CHICAGO -- Dwyane Wade made his Chicago homecoming a memorable affair, contributing 22 points, six rebounds and five assists to the Bulls'' 105-99 win over the Boston Celtics on Thursday night.',
                         'In his first regular-season appearance as a member of the Bulls, Wade had fans cheering from start to finish as he authored the beginning of a new chapter in his Hall of Fame career.
After being announced as "from Chicago" in the starting lineup introductions, Wade, who is from Robbins, Illinois, took a knee for a moment before making his way through a line of high-fives with some of his teammates.
"I''ve been waiting on that moment for a long time," Wade said. "I know it was special, obviously, for my family who was here. They''ve been waiting on it probably just as long. I just took that moment just to thank God for giving me this opportunity to be here, to do these things, to have this career I have. And to be able to make a decision on my own. And put myself in a position where I can live a dream out. I was very thankful in that moment. Took that knee to just thank the Lord and hear the cheers in the crowd and take in a moment. And then, it''s game time."
Wade signed with the Bulls over the summer after 13 seasons with the Miami Heat. He has been heralded throughout training camp as a solid leader and a player his younger teammates can learn from, alongside veteran point guard Rajon Rondo.Making his presence known throughout the game, Wade went 7-for-18 from the field and hit the biggest shot of the night, a 3-pointer with 26.3 seconds left that gave the Bulls a five-point lead they would not relinquish.
Wade said he "had an out-of-body experience" after knocking down the 3, which included a throat slash toward the Celtics.
"We''re not the team that everyone is analytically putting together," Wade said of the new-look Bulls. "But we''re a team of guys who can compete. We''re a team of guys who have pride. We''re a team of guys with talent. Once you make it all work together, it doesn''t matter about analytics or the game. It''s about players. And it''s about going out there and competing. And we were able to do that tonight. So we''re able to do that on a consistent basis. Who knows if the 3''s going to go in, but we know if we compete and give that effort, we''ll have a chance to win every night, and that''s all you can ask for in this league."
Wade''s performance underscored why the Bulls'' front office was so happy to land him over the summer. Not only did he help lead Chicago to victory, but he also gave the team a jolt of energy throughout the night and made plays when the game was on the line.
"He means a lot to this team," Bulls power forward Taj Gibson said. "We need him to be the Wade he''s always been. The guy who''s not afraid to attack. The guy''s who''s not afraid to take big shots like you see late in the game. ... When D-Wade took that shot, he made it, his expressions, how he was jumping around, his swag -- it was kind of awkward, because I''m used to him kind of doing that against us on the opposing side. But it was a great thing. I was happy we got a win."
Butler, who the Bulls hope can mature under Wade''s tutelage, sang his new teammate''s praises as well.
"That''s one less player I got to guard in this league, to tell you the truth, so I''m excited about that," Butler said of Wade. "But the way the game slows down for him, he knows where guys are going to be. It''s hard to do, but that''s what happens whenever you play 13, going on 14, years in this league. He''s so much smarter than a lot of guys, using his body and his athleticism to his advantage, so I''m taking note."','2016-10-29');

INSERT INTO NEWS VALUES (NULL,
                         'First-ever dinosaur brain tissue found',
                         'Ilya',
                         'What was going on in dinosaurs'' noggins as they dwelled in Cretaceous forests, stalking fierce prey or sitting on a nest of giant eggs?',
                         'Paleontologists may never know the answer to these questions, but they just got one step closer with the first-ever discovery of brain tissue from a dinosaur.
And it’s tiny.
The brainy finding looked like an unassuming brown pebble when a fossil hunter in Sussex, England, found it more than a decade ago. Discovering any soft tissue from a dinosaur is rare since that material degrades faster than other types of tissue, and dinosaurs lived more than 66 million years ago. [See Images of the Fossilized Dinosaur Brain Tissue]
This particular soft tissue was essentially pickled when the dinosaur died, according to the researchers, which is why it was so well-preserved.
“What we think happened is that this particular dinosaur died in or near a body of water, and its head ended up partially buried in the sediment at the bottom,” co-author David Norman, a scientist at the University of Cambridge, said in a statement. “Since the water had little oxygen and was very acidic, the soft tissues of the brain were likely preserved and cast before the rest of its body was buried in the sediment.”
Using a scanning electron microscope (SEM) — which produces images in fine detail by moving a beam of electrons over an object — the researchers identified different structures within the pebble-size tissue. In the images, they could make out meninges (tissue that surrounds the brain), strands of collagen and blood vessels, and structures that could be from the brain’s cortex (the outer layer of the brain).
Norman and his colleagues determined the brain tissue was likely from a species similar to Iguanodon, a large herbivorous dinosaur that lived during the early Cretaceous period, about 133 million years ago. The structure seen within the fossilized brain tissue showed similarities to that found in birds and crocodiles — dinosaurs’ modern-day descendants.
“It was indeed structured rather like that seen typically in reptiles,” Norman told Live Science. “It also does not show that dinosaurs were necessarily very smart — their brains did not fill their braincases in this instance.”In reptiles, and assumed for dinosaurs, the brain only takes up about half of the space within the cranial cavity. The rest of the space is a dense region of blood vessels that surrounds the brain. Based on the structures seen in the fossilized brain, the researchers said it is consistent with reptiles.
Though some dinosaurs are believed to have sported quite large brains, namely those that led to modern birds, Norman said this particular fossil does not display such size.
The researchers also cautioned against drawing conclusions about the intelligence of dinosaurs from this particular fossil. However, they do posit that this dinosaur and its relatives had relatively complex behaviors.
“It is reasonable to suppose that iguanodontian dinosaurs of this type were moderately complex behaviorally (no less so than modern crocodilians, for example),” the researchers wrote.
Their findings were published Oct. 27 in a Special Publication of the Geological Society of London, in tribute to Martin Brasier of the University of Oxford, who died in 2014. Brasier and Norman coordinated the research into this particular fossil during the years before Brasier’s death in a traffic accident.','2016-10-29');